### ISSUE TITLE
Remove outdated entries from metamodel.yaml

### ISSUE THREAD

**Issue by tudorache** [who-icatx/whofic-models#19]
From metamodel.yaml, it seems we don't need:

-synonym (which is modeled there as an annotation property):
```  
synonym:
    subproperty_of: baseIndex
    range: BaseIndexTerm
    multivalued: true
    implements:
      - owl:AnnotationProperty
```

Is permissibleValues still needed?

```
enums:
  IndexType:
    implements:
      - owl:NamedIndividual
    description: types of index terms
    permissible_values:
        Synonym:
        Narrower:
```

Maybe there are other cases, as well.
